### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eklemen** [eklemen/study-buddy#8]
### ToDo: New features

**Update 6-21**
- [ ] Change login page style
- [ ] move stuff to json format?
- [ ] more stuff
- [ ] add transition to hamburger
- [X] Create Login with twitter 
- [ ] Auto tweet or fb post when user logs in, or creates a group? hmm...
- [ ] fiverr logo would be sweet

**GROUP DETAILS (create)**
- [ ] Add _instructor_ selection
- Add more locations to choose from:
  - [ ] **Change school** dropdown menu (conditional for following form items)
  - [ ] starbucks on UCF campus
  - [ ] AKS (arena and Ferrell Commons)
  - no blueprint maps available
- [ ] More form boxes to include optional details  
  - Possible categories:
    - Study duration
    - Materials covered
    - study habits/environment (talkative, lecture-style, silent but open to questions)
    - additional notes about the group

**LIST VIEW (browse)** 
- [ ] All optional information is shown when group is clicked  
  **_Will need more planning**_
  - [ ] Students can _join_ groups

**BUG LIST**
- [X] Manage page needs to display differently if no group is made
- [ ] manage page, need to have drop down for location, not a manual enter
